:cmock:
  :verbosity: 3
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :plugins:
    - :ignore
    - :ignore_arg
    - :expect_any_args
    - :array
    - :callback
    - :return_thru_ptr
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
  :treat_externs: :include  # Now the externed functions will be mocked.