name: selftests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: install tools and run selftests
      run: .\spl.ps1 -build -target selftests -installMandatory
      shell: powershell

    - uses: actions/upload-artifact@v2
      with:
        name: code-coverage.zip
        retention-days: 90
        path: build/**/coverage/*
        if-no-files-found: error
